---
root: true
#  https://eslint.org/docs/rules/
env:
  node: true
  es2020: true
parserOptions:
  ecmaVersion: 2022
  sourceType: module
globals:
  alert: false
  window: false
  history: false
  document: false
  navigator: false
  requestAnimationFrame: false
  PoweredUP: false
  JoyStick: false
extends:
  - "eslint:recommended"
  - prettier
rules:
  no-var: [error]
  no-unused-vars: [error, { argsIgnorePattern: "" }]
  no-restricted-modules: [error, child_process]
  no-eval: [error]
  no-implied-eval: [error]
  strict: [warn]
  curly: [error]
  no-constant-condition: [error, { checkLoops: false }]
